name: Build and Push Docker Image with Tags

on:
  push:
    tags:
      - 'lux-v*'  # Trigger only when pushing tags like lux-v1.0.0

jobs:
  # Define the job for building and pushing Docker images
  build-and-push:
    # Specify the runner environment as Ubuntu latest version
    runs-on: ubuntu-latest

    # List the sequence of steps to execute in this job
    steps:
      # Step 1: Check out the repository code to the runner
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Set up Docker Buildx for multi-platform image building
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Step 3: Authenticate with DockerHub using stored credentials
      - name: Log in to DockerHub
        uses: docker/login-action@v3
        with:
          # Use repository secrets for secure credential storage
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_TOKEN }}

      # Step 4: Build the Docker image and push it to DockerHub
      - name: Build and push Docker image with tag
        uses: docker/build-push-action@v5
        with:
          # Specify build context as current directory
          context: .
          # Path to the Dockerfile
          file: ./Dockerfile
          # Enable pushing to registry
          push: true
          # Define image tags - one with version from git tag, one as latest
          tags: |
            luximo1/otuvedo-ceg3120:${{ github.ref_name }}
            luximo1/otuvedo-ceg3120:latest

            # Add this new step
      - name: Trigger deployment webhook
        if: success()
        run: |
          curl -X POST http://54.227.249.4:9000/hooks/redeploy \
            -H "X-Hook-Token: luximo1-deploy-token" \
            -H "Content-Type: application/json" \
            -d '{"ref": "${{ github.ref }}", "repository": "${{ github.repository }}"}'